### ISSUE TITLE
PHP unit fails after installation

### ISSUE THREAD

**Issue by wardy484** [johnnymast/myio#55]
### Expected behavior
All tests should pass. 

### Actual behavior
3 Errors occur. 

`1) Tests\Unit\UserRoleTest::can_create_user_as_an_administrator
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Doctrine\DBAL\Driver\PDOSqlite\Driver' not found`

`2) Tests\Unit\UserRoleTest::can_create_normal_user
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Doctrine\DBAL\Driver\PDOSqlite\Driver' not found`

`Caused by
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.email`

### Steps to reproduce the behavior

1. Installing by running git clone on the repository. 
2. Composer install
3. php artisan myio:install - followed through and configured correctly
4. php artisan migrate
5. php artisan myio:testenv

All the above steps were followed with no issues. 

However when running phpunit the errors mentioned previously occured. 

This was done in Laravel Homestead on Windows 10.

**Comment by wardy484** [comment]
Following the advice on this post:
[https://laracasts.com/discuss/channels/laravel/laravel-51-class-doctrinedbaldriverpdosqlitedriver-not-found](url)

Adding: "doctrine/dbal": "^2.5" to composer.json and running composer update seems to fix the initial dependency issues.  Now a new set of errors are generated:

`1) Tests\Unit\UserRoleTest::can_create_user_as_an_administrator
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint failed: users.email (SQL: insert into "users" ("name", "email", "password", "remember_token", "updated_at", "created_at") values (Jonny Admin, jonny@myio.com, $2y$10$rH/hxNXYM.rGFQPjHigTduMj2YqbkbTaaVbCxCR./fIVTQiZa3tIy, NecwUfqpmU, 2017-03-22 21:42:01, 2017-03-22 21:42:01))`

`2) Tests\Unit\UserRoleTest::can_create_normal_user
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'activated' on table 'users'.`

`3) Tests\Unit\UserRoleTest::normal_user_cannot_have_administrtaor_role
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'activated' on table 'users'.`

**Comment by johnnymast** [comment]
Ah that simple? Lol should be a quick fix.

**Comment by stevepop** [comment]
The issue above was totally different from ours but this is not fixed with explanation in the commit.

**Comment by stevepop** [comment]
Issue is now resolved with PR https://github.com/johnnymast/myio/pull/56

**Comment by johnnymast** [comment]
The issue is still here @wardy484 was right adding 

"doctrine/dbal": "^2.5"

Fixes this issue, let me fix it.

**Comment by johnnymast** [comment]
This should do it.
